Trying to fix failing build TickPriceHistoryServiceClientFactory.cs(3,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [/jenkins/workspace/RedDeer.Surveillance/src/Surveillance.Data.Universe.Refinitiv/Surveillance.Data.Universe.Refinitiv.csproj]